DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstname TEXT NOT NULL UNIQUE,
    lastname TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    phoneNumber INTEGER NOT NULL UNIQUE,
    password TEXT NOT NULL
);